-- ============================================================
--     _      _      ____
--    / \    | |    | __ )
--   / _ \   | |    |  _ \
--  / ___ \  | |___ | |_) |
-- /_/   \_\ |_____||____/
--
--  AdaLogic BASIC (ALB)
--  Copyright 2014-2026 Rocky L. Oliver d/b/a Oliver Softworks
--
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.
--
--  Contact: contact@alb-lang.org
--  https://alb-lang.org | https://alb-lang.com | https://alb-lang.dev
-- ============================================================

pragma SPARK_Mode (On);
with Opcodes;        use Opcodes;
with ALB_Types;      use ALB_Types;
with Range_Spec;     use Range_Spec;
with Numerus_Magnus; use Numerus_Magnus; -- Unlocking da U8 type!

package Emitter is

   -- Da absolute limit o' generated bytecode (Rule 3: Nae heap)
   Max_Bytecode_Size : constant := 8192;
   
   type Bytecode_Buffer is array (1 .. Max_Bytecode_Size) of U8;

   type Emitter_State is record
      Buffer : Bytecode_Buffer := (others => 0);
      IP     : Natural := 0; -- Instruction Pointer (Bytes emitted)
   end record;

   -- Core Operations
   procedure Init_Emitter (Success : out Boolean);
   
   -- Emits a single Opcode
   procedure Emit_Op (Op : in ALB_Opcode; Success : out Boolean);
   
   -- Emits an 8-bit Operand (like a variable index or peerie constant)
   procedure Emit_U8 (Val : in U8; Success : out Boolean);
   
end Emitter;
